version: "3.9"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: gmg-api
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./api/app:/app/app
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: gmg-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-gmg}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-gmg}
      POSTGRES_DB: ${POSTGRES_DB:-gmg}
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: gmg-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  dbdata:
